---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sampleapp
    version: prod
  name: sampleapp
  namespace: sampleapp
spec:
  ports:
    - name: metrics
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: sampleapp
  type: ClusterIP
